#!/usr/bin/env python3
"""
Convert PNG images in source/ to RGB565 C arrays.

Usage: python convert_png_to_rgb565.py

Scans *.png in the script's directory, converts each to a C-compatible
RGB565 array with color-key (magenta = transparent). Outputs png_assets.h.
"""
import os
import sys
from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(SCRIPT_DIR, "png_assets.h")

# RGB565 magenta: R=31 G=0 B=31 → (31<<11)|(0<<5)|31 = 0xF81F
COLOR_KEY = 0xF81F


def rgba_to_rgb565(r, g, b, a):
    """Convert RGBA to RGB565. Transparent pixels → magenta key."""
    if a < 128:
        return COLOR_KEY
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    return (r5 << 11) | (g6 << 5) | b5


def convert_png(filepath):
    """Convert a single PNG to RGB565 array. Returns (name, w, h, data)."""
    img = Image.open(filepath)
    if img.mode != "RGBA":
        img = img.convert("RGBA")

    w, h = img.size
    pixels = list(img.getdata())
    data = [rgba_to_rgb565(r, g, b, a) for r, g, b, a in pixels]
    return w, h, data


def format_array(data, w, indent=8):
    """Format pixel data as C array rows, one row per image row."""
    lines = []
    for y, row_start in enumerate(range(0, len(data), w)):
        row_pixels = data[row_start:row_start + w]
        hex_vals = ", ".join(f"0x{p:04X}" for p in row_pixels)
        lines.append(f"{' ' * indent}{hex_vals},")
    return "\n".join(lines)


def main():
    png_files = sorted(
        f for f in os.listdir(SCRIPT_DIR)
        if f.lower().endswith(".png")
    )

    if not png_files:
        print("No PNG files found in", SCRIPT_DIR)
        sys.exit(1)

    entries = []
    for fname in png_files:
        filepath = os.path.join(SCRIPT_DIR, fname)
        name = os.path.splitext(fname)[0].replace("-", "_").replace(" ", "_")
        w, h, data = convert_png(filepath)
        entries.append((name, w, h, data))
        print(f"  {fname} → {w}×{h} ({w*h} pixels)")

    # Generate header
    lines = []
    lines.append("// Auto-generated by convert_png_to_rgb565.py")
    lines.append("// DO NOT EDIT BY HAND")
    lines.append("// Source images: main/source/*.png")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append('#include <stdint.h>')
    lines.append("")
    lines.append("// clang-format off")
    lines.append("")

    for name, w, h, data in entries:
        macro_prefix = name.upper()
        lines.append(f"/// {name}.png  ({w}×{h})")
        lines.append(f"#define PNG_{macro_prefix}_W  {w}")
        lines.append(f"#define PNG_{macro_prefix}_H  {h}")
        lines.append(f"static const uint16_t png_{name}_data[{w * h}] = {{")
        lines.append(format_array(data, w))
        lines.append("};")
        lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\nGenerated: {OUTPUT}")
    print(f"  {len(entries)} sprite(s)")
    for name, w, h, _ in entries:
        print(f"    png_{name}_data[{w}×{h}]  — use PNG_{name.upper()}_W / _H")


if __name__ == "__main__":
    main()
